//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunicacion
    {
        public int id_comunicacion { get; set; }
        public Nullable<int> id_propiedad { get; set; }
        public string asunto { get; set; }
        public string persona_gestor { get; set; }
        public Nullable<int> nivel_interes { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_contactos { get; set; }
    
        public virtual Contactos Contactos { get; set; }
    }
}
