//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedad_Contactos
    {
        public int id_propiedad_contactos { get; set; }
        public Nullable<int> id_contactos { get; set; }
        public Nullable<int> id_propiedad { get; set; }
    
        public virtual Contactos Contactos { get; set; }
        public virtual Propiedad Propiedad { get; set; }
    }
}
