//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propiedad()
        {
            this.amenidades_propiedad = new HashSet<amenidades_propiedad>();
            this.Propiedad_Contactos = new HashSet<Propiedad_Contactos>();
            this.Usuario_Propiedades = new HashSet<Usuario_Propiedades>();
        }
    
        public int id_propiedad { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<double> terreno { get; set; }
        public Nullable<int> ciudad { get; set; }
        public Nullable<int> num_cuartos { get; set; }
        public Nullable<int> num_baños { get; set; }
        public Nullable<int> num_pisos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amenidades_propiedad> amenidades_propiedad { get; set; }
        public virtual Ciudad Ciudad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propiedad_Contactos> Propiedad_Contactos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Propiedades> Usuario_Propiedades { get; set; }
    }
}
