//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Propiedades
    {
        public int id_usuario_propiedad { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_propiedad { get; set; }
    
        public virtual Propiedad Propiedad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
